name: seekqr_app
repository: https://github.com/jhondiaz/MonorepoSeekQrApp

packages:
  - apps/*
  - packages/*


command:
  dev_dependencies:

    build_runner: ^2.4.15

scripts:
  bootstrap:
    run: melos exec flutter pub get
  test:
    run: melos exec flutter test
  build:
    run: melos exec flutter build apk
  release:
    run: melos exec --scope="seekqr_app" -- flutter run --release
  generate:flutter:
     run: melos exec flutter pub run build_runner build
     description: Build all generated files for Flutter packages in this project.





